// Generated by gencpp from file jason_ros_msgs/Action.msg
// DO NOT EDIT!


#ifndef JASON_ROS_MSGS_MESSAGE_ACTION_H
#define JASON_ROS_MSGS_MESSAGE_ACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jason_ros_msgs
{
template <class ContainerAllocator>
struct Action_
{
  typedef Action_<ContainerAllocator> Type;

  Action_()
    : header()
    , action_name()
    , parameters()  {
    }
  Action_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , action_name(_alloc)
    , parameters(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_name_type;
  _action_name_type action_name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _parameters_type;
  _parameters_type parameters;





  typedef boost::shared_ptr< ::jason_ros_msgs::Action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jason_ros_msgs::Action_<ContainerAllocator> const> ConstPtr;

}; // struct Action_

typedef ::jason_ros_msgs::Action_<std::allocator<void> > Action;

typedef boost::shared_ptr< ::jason_ros_msgs::Action > ActionPtr;
typedef boost::shared_ptr< ::jason_ros_msgs::Action const> ActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jason_ros_msgs::Action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jason_ros_msgs::Action_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jason_ros_msgs::Action_<ContainerAllocator1> & lhs, const ::jason_ros_msgs::Action_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.action_name == rhs.action_name &&
    lhs.parameters == rhs.parameters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jason_ros_msgs::Action_<ContainerAllocator1> & lhs, const ::jason_ros_msgs::Action_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jason_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jason_ros_msgs::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jason_ros_msgs::Action_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jason_ros_msgs::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jason_ros_msgs::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jason_ros_msgs::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jason_ros_msgs::Action_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jason_ros_msgs::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60b115de72e5d2f7244b28be9903e13e";
  }

  static const char* value(const ::jason_ros_msgs::Action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60b115de72e5d2f7ULL;
  static const uint64_t static_value2 = 0x244b28be9903e13eULL;
};

template<class ContainerAllocator>
struct DataType< ::jason_ros_msgs::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jason_ros_msgs/Action";
  }

  static const char* value(const ::jason_ros_msgs::Action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jason_ros_msgs::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string action_name\n"
"string[] parameters\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::jason_ros_msgs::Action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jason_ros_msgs::Action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.action_name);
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jason_ros_msgs::Action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jason_ros_msgs::Action_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "action_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action_name);
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.parameters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JASON_ROS_MSGS_MESSAGE_ACTION_H
