// Generated by gencpp from file jason_ros_msgs/Perception.msg
// DO NOT EDIT!


#ifndef JASON_ROS_MSGS_MESSAGE_PERCEPTION_H
#define JASON_ROS_MSGS_MESSAGE_PERCEPTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jason_ros_msgs
{
template <class ContainerAllocator>
struct Perception_
{
  typedef Perception_<ContainerAllocator> Type;

  Perception_()
    : header()
    , perception_name()
    , parameters()
    , update(false)  {
    }
  Perception_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , perception_name(_alloc)
    , parameters(_alloc)
    , update(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _perception_name_type;
  _perception_name_type perception_name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _parameters_type;
  _parameters_type parameters;

   typedef uint8_t _update_type;
  _update_type update;





  typedef boost::shared_ptr< ::jason_ros_msgs::Perception_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jason_ros_msgs::Perception_<ContainerAllocator> const> ConstPtr;

}; // struct Perception_

typedef ::jason_ros_msgs::Perception_<std::allocator<void> > Perception;

typedef boost::shared_ptr< ::jason_ros_msgs::Perception > PerceptionPtr;
typedef boost::shared_ptr< ::jason_ros_msgs::Perception const> PerceptionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jason_ros_msgs::Perception_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jason_ros_msgs::Perception_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jason_ros_msgs::Perception_<ContainerAllocator1> & lhs, const ::jason_ros_msgs::Perception_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.perception_name == rhs.perception_name &&
    lhs.parameters == rhs.parameters &&
    lhs.update == rhs.update;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jason_ros_msgs::Perception_<ContainerAllocator1> & lhs, const ::jason_ros_msgs::Perception_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jason_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jason_ros_msgs::Perception_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jason_ros_msgs::Perception_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jason_ros_msgs::Perception_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jason_ros_msgs::Perception_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jason_ros_msgs::Perception_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jason_ros_msgs::Perception_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jason_ros_msgs::Perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "547f6a7c40005d1eac4746fdc9b3ee7b";
  }

  static const char* value(const ::jason_ros_msgs::Perception_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x547f6a7c40005d1eULL;
  static const uint64_t static_value2 = 0xac4746fdc9b3ee7bULL;
};

template<class ContainerAllocator>
struct DataType< ::jason_ros_msgs::Perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jason_ros_msgs/Perception";
  }

  static const char* value(const ::jason_ros_msgs::Perception_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jason_ros_msgs::Perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string perception_name\n"
"string[] parameters\n"
"bool update\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::jason_ros_msgs::Perception_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jason_ros_msgs::Perception_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.perception_name);
      stream.next(m.parameters);
      stream.next(m.update);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Perception_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jason_ros_msgs::Perception_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jason_ros_msgs::Perception_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "perception_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.perception_name);
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.parameters[i]);
    }
    s << indent << "update: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JASON_ROS_MSGS_MESSAGE_PERCEPTION_H
